/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'Income' : IDL.Null,
  'Expense' : IDL.Null,
});
export const BudgetCategory = IDL.Record({
  'id' : IDL.Text,
  'categoryType' : TransactionType,
  'monthlyLimit' : IDL.Float64,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const FinancialModel = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'initialAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'annualReturn' : IDL.Float64,
  'years' : IDL.Int,
  'monthlyContribution' : IDL.Float64,
});
export const FinancialRule = IDL.Record({
  'id' : IDL.Text,
  'ruleType' : IDL.Text,
  'action' : IDL.Text,
  'threshold' : IDL.Float64,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'condition' : IDL.Text,
});
export const Goal = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'deadline' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'currentAmount' : IDL.Float64,
});
export const Loan = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Float64,
  'currentBalance' : IDL.Float64,
  'name' : IDL.Text,
  'loanType' : IDL.Text,
  'termMonths' : IDL.Int,
  'interestRate' : IDL.Float64,
  'notes' : IDL.Text,
  'monthlyPayment' : IDL.Float64,
  'startDate' : IDL.Text,
});
export const PlannerEvent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
  'eventType' : IDL.Text,
});
export const AssetType = IDL.Variant({
  'ETF' : IDL.Null,
  'RealEstate' : IDL.Null,
  'MutualFund' : IDL.Null,
  'Commodity' : IDL.Null,
  'FixedIncome' : IDL.Null,
  'Crypto' : IDL.Null,
  'Other' : IDL.Null,
  'Retirement' : IDL.Null,
});
export const PortfolioHolding = IDL.Record({
  'id' : IDL.Text,
  'ticker' : IDL.Text,
  'name' : IDL.Text,
  'currentValue' : IDL.Float64,
  'notes' : IDL.Text,
  'quantity' : IDL.Float64,
  'costBasis' : IDL.Float64,
  'assetType' : AssetType,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'transactionType' : TransactionType,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'account' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DashboardSummary = IDL.Record({
  'modelCount' : IDL.Nat,
  'totalIncome' : IDL.Float64,
  'loanCount' : IDL.Nat,
  'goalCount' : IDL.Nat,
  'budgetCategoryCount' : IDL.Nat,
  'totalExpenses' : IDL.Float64,
  'portfolioCount' : IDL.Nat,
  'eventCount' : IDL.Nat,
  'ruleCount' : IDL.Nat,
  'transactionCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBudgetCategory' : IDL.Func([BudgetCategory], [BudgetCategory], []),
  'createFinancialModel' : IDL.Func([FinancialModel], [FinancialModel], []),
  'createFinancialRule' : IDL.Func([FinancialRule], [FinancialRule], []),
  'createGoal' : IDL.Func([Goal], [Goal], []),
  'createLoan' : IDL.Func([Loan], [Loan], []),
  'createPlannerEvent' : IDL.Func([PlannerEvent], [PlannerEvent], []),
  'createPortfolioHolding' : IDL.Func(
      [PortfolioHolding],
      [PortfolioHolding],
      [],
    ),
  'createTransaction' : IDL.Func([Transaction], [Transaction], []),
  'deleteBudgetCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteFinancialModel' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteFinancialRule' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteGoal' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteLoan' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePlannerEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePortfolioHolding' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllBudgetCategories' : IDL.Func([], [IDL.Vec(BudgetCategory)], ['query']),
  'getAllFinancialModels' : IDL.Func([], [IDL.Vec(FinancialModel)], ['query']),
  'getAllFinancialRules' : IDL.Func([], [IDL.Vec(FinancialRule)], ['query']),
  'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getAllLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
  'getAllPlannerEvents' : IDL.Func([], [IDL.Vec(PlannerEvent)], ['query']),
  'getAllPortfolioHoldings' : IDL.Func(
      [],
      [IDL.Vec(PortfolioHolding)],
      ['query'],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getBudgetCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BudgetCategory)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getFinancialModel' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FinancialModel)],
      ['query'],
    ),
  'getFinancialRule' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FinancialRule)],
      ['query'],
    ),
  'getGoal' : IDL.Func([IDL.Text], [IDL.Opt(Goal)], ['query']),
  'getLoan' : IDL.Func([IDL.Text], [IDL.Opt(Loan)], ['query']),
  'getNetWorth' : IDL.Func([], [IDL.Float64], ['query']),
  'getPlannerEvent' : IDL.Func([IDL.Text], [IDL.Opt(PlannerEvent)], ['query']),
  'getPortfolioHolding' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PortfolioHolding)],
      ['query'],
    ),
  'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBudgetCategory' : IDL.Func(
      [IDL.Text, BudgetCategory],
      [IDL.Opt(BudgetCategory)],
      [],
    ),
  'updateFinancialModel' : IDL.Func(
      [IDL.Text, FinancialModel],
      [IDL.Opt(FinancialModel)],
      [],
    ),
  'updateFinancialRule' : IDL.Func(
      [IDL.Text, FinancialRule],
      [IDL.Opt(FinancialRule)],
      [],
    ),
  'updateGoal' : IDL.Func([IDL.Text, Goal], [IDL.Opt(Goal)], []),
  'updateLoan' : IDL.Func([IDL.Text, Loan], [IDL.Opt(Loan)], []),
  'updatePlannerEvent' : IDL.Func(
      [IDL.Text, PlannerEvent],
      [IDL.Opt(PlannerEvent)],
      [],
    ),
  'updatePortfolioHolding' : IDL.Func(
      [IDL.Text, PortfolioHolding],
      [IDL.Opt(PortfolioHolding)],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [IDL.Text, Transaction],
      [IDL.Opt(Transaction)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'Income' : IDL.Null,
    'Expense' : IDL.Null,
  });
  const BudgetCategory = IDL.Record({
    'id' : IDL.Text,
    'categoryType' : TransactionType,
    'monthlyLimit' : IDL.Float64,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const FinancialModel = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'initialAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'annualReturn' : IDL.Float64,
    'years' : IDL.Int,
    'monthlyContribution' : IDL.Float64,
  });
  const FinancialRule = IDL.Record({
    'id' : IDL.Text,
    'ruleType' : IDL.Text,
    'action' : IDL.Text,
    'threshold' : IDL.Float64,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'condition' : IDL.Text,
  });
  const Goal = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'deadline' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'currentAmount' : IDL.Float64,
  });
  const Loan = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Float64,
    'currentBalance' : IDL.Float64,
    'name' : IDL.Text,
    'loanType' : IDL.Text,
    'termMonths' : IDL.Int,
    'interestRate' : IDL.Float64,
    'notes' : IDL.Text,
    'monthlyPayment' : IDL.Float64,
    'startDate' : IDL.Text,
  });
  const PlannerEvent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
    'eventType' : IDL.Text,
  });
  const AssetType = IDL.Variant({
    'ETF' : IDL.Null,
    'RealEstate' : IDL.Null,
    'MutualFund' : IDL.Null,
    'Commodity' : IDL.Null,
    'FixedIncome' : IDL.Null,
    'Crypto' : IDL.Null,
    'Other' : IDL.Null,
    'Retirement' : IDL.Null,
  });
  const PortfolioHolding = IDL.Record({
    'id' : IDL.Text,
    'ticker' : IDL.Text,
    'name' : IDL.Text,
    'currentValue' : IDL.Float64,
    'notes' : IDL.Text,
    'quantity' : IDL.Float64,
    'costBasis' : IDL.Float64,
    'assetType' : AssetType,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'transactionType' : TransactionType,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'account' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const DashboardSummary = IDL.Record({
    'modelCount' : IDL.Nat,
    'totalIncome' : IDL.Float64,
    'loanCount' : IDL.Nat,
    'goalCount' : IDL.Nat,
    'budgetCategoryCount' : IDL.Nat,
    'totalExpenses' : IDL.Float64,
    'portfolioCount' : IDL.Nat,
    'eventCount' : IDL.Nat,
    'ruleCount' : IDL.Nat,
    'transactionCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBudgetCategory' : IDL.Func([BudgetCategory], [BudgetCategory], []),
    'createFinancialModel' : IDL.Func([FinancialModel], [FinancialModel], []),
    'createFinancialRule' : IDL.Func([FinancialRule], [FinancialRule], []),
    'createGoal' : IDL.Func([Goal], [Goal], []),
    'createLoan' : IDL.Func([Loan], [Loan], []),
    'createPlannerEvent' : IDL.Func([PlannerEvent], [PlannerEvent], []),
    'createPortfolioHolding' : IDL.Func(
        [PortfolioHolding],
        [PortfolioHolding],
        [],
      ),
    'createTransaction' : IDL.Func([Transaction], [Transaction], []),
    'deleteBudgetCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteFinancialModel' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteFinancialRule' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteGoal' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteLoan' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePlannerEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePortfolioHolding' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllBudgetCategories' : IDL.Func(
        [],
        [IDL.Vec(BudgetCategory)],
        ['query'],
      ),
    'getAllFinancialModels' : IDL.Func(
        [],
        [IDL.Vec(FinancialModel)],
        ['query'],
      ),
    'getAllFinancialRules' : IDL.Func([], [IDL.Vec(FinancialRule)], ['query']),
    'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getAllLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
    'getAllPlannerEvents' : IDL.Func([], [IDL.Vec(PlannerEvent)], ['query']),
    'getAllPortfolioHoldings' : IDL.Func(
        [],
        [IDL.Vec(PortfolioHolding)],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getBudgetCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BudgetCategory)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getFinancialModel' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FinancialModel)],
        ['query'],
      ),
    'getFinancialRule' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FinancialRule)],
        ['query'],
      ),
    'getGoal' : IDL.Func([IDL.Text], [IDL.Opt(Goal)], ['query']),
    'getLoan' : IDL.Func([IDL.Text], [IDL.Opt(Loan)], ['query']),
    'getNetWorth' : IDL.Func([], [IDL.Float64], ['query']),
    'getPlannerEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PlannerEvent)],
        ['query'],
      ),
    'getPortfolioHolding' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PortfolioHolding)],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBudgetCategory' : IDL.Func(
        [IDL.Text, BudgetCategory],
        [IDL.Opt(BudgetCategory)],
        [],
      ),
    'updateFinancialModel' : IDL.Func(
        [IDL.Text, FinancialModel],
        [IDL.Opt(FinancialModel)],
        [],
      ),
    'updateFinancialRule' : IDL.Func(
        [IDL.Text, FinancialRule],
        [IDL.Opt(FinancialRule)],
        [],
      ),
    'updateGoal' : IDL.Func([IDL.Text, Goal], [IDL.Opt(Goal)], []),
    'updateLoan' : IDL.Func([IDL.Text, Loan], [IDL.Opt(Loan)], []),
    'updatePlannerEvent' : IDL.Func(
        [IDL.Text, PlannerEvent],
        [IDL.Opt(PlannerEvent)],
        [],
      ),
    'updatePortfolioHolding' : IDL.Func(
        [IDL.Text, PortfolioHolding],
        [IDL.Opt(PortfolioHolding)],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [IDL.Text, Transaction],
        [IDL.Opt(Transaction)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };