/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminModuleAccess {
  'principal' : Principal,
  'modules' : Array<[string, boolean]>,
}
export interface AdminUserInfo {
  'principal' : Principal,
  'isBlocked' : boolean,
  'role' : UserRole,
  'blockedReason' : string,
  'profile' : [] | [UserProfile],
}
export type AssetType = { 'ETF' : null } |
  { 'RealEstate' : null } |
  { 'MutualFund' : null } |
  { 'Commodity' : null } |
  { 'FixedIncome' : null } |
  { 'Crypto' : null } |
  { 'Other' : null } |
  { 'Retirement' : null };
export interface BlockedStatus { 'blocked' : boolean, 'reason' : string }
export interface BudgetCategory {
  'id' : string,
  'categoryType' : TransactionType,
  'monthlyLimit' : number,
  'name' : string,
  'color' : string,
}
export interface DashboardSummary {
  'modelCount' : bigint,
  'totalIncome' : number,
  'loanCount' : bigint,
  'goalCount' : bigint,
  'budgetCategoryCount' : bigint,
  'totalExpenses' : number,
  'portfolioCount' : bigint,
  'eventCount' : bigint,
  'ruleCount' : bigint,
  'transactionCount' : bigint,
}
export interface FinancialModel {
  'id' : string,
  'name' : string,
  'initialAmount' : number,
  'notes' : string,
  'annualReturn' : number,
  'years' : bigint,
  'monthlyContribution' : number,
}
export interface FinancialRule {
  'id' : string,
  'ruleType' : string,
  'action' : string,
  'threshold' : number,
  'name' : string,
  'isActive' : boolean,
  'condition' : string,
}
export interface Goal {
  'id' : string,
  'name' : string,
  'deadline' : string,
  'targetAmount' : number,
  'notes' : string,
  'category' : string,
  'currentAmount' : number,
}
export interface Loan {
  'id' : string,
  'principal' : number,
  'currentBalance' : number,
  'name' : string,
  'loanType' : string,
  'termMonths' : bigint,
  'interestRate' : number,
  'notes' : string,
  'monthlyPayment' : number,
  'startDate' : string,
}
export interface PlannerEvent {
  'id' : string,
  'title' : string,
  'isCompleted' : boolean,
  'date' : string,
  'notes' : string,
  'amount' : number,
  'eventType' : string,
}
export interface PortfolioHolding {
  'id' : string,
  'ticker' : string,
  'name' : string,
  'currentValue' : number,
  'notes' : string,
  'quantity' : number,
  'costBasis' : number,
  'assetType' : AssetType,
}
export interface Transaction {
  'id' : string,
  'categoryId' : string,
  'transactionType' : TransactionType,
  'date' : string,
  'description' : string,
  'account' : string,
  'amount' : number,
}
export type TransactionType = { 'Income' : null } |
  { 'Expense' : null };
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminBlockUser' : ActorMethod<[Principal, boolean, string], undefined>,
  'adminGetAllUserModuleAccess' : ActorMethod<[], Array<AdminModuleAccess>>,
  'adminGetAllUsers' : ActorMethod<[], Array<AdminUserInfo>>,
  'adminSetModuleAccess' : ActorMethod<[Principal, string, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBudgetCategory' : ActorMethod<[BudgetCategory], BudgetCategory>,
  'createFinancialModel' : ActorMethod<[FinancialModel], FinancialModel>,
  'createFinancialRule' : ActorMethod<[FinancialRule], FinancialRule>,
  'createGoal' : ActorMethod<[Goal], Goal>,
  'createLoan' : ActorMethod<[Loan], Loan>,
  'createPlannerEvent' : ActorMethod<[PlannerEvent], PlannerEvent>,
  'createPortfolioHolding' : ActorMethod<[PortfolioHolding], PortfolioHolding>,
  'createTransaction' : ActorMethod<[Transaction], Transaction>,
  'deleteBudgetCategory' : ActorMethod<[string], boolean>,
  'deleteFinancialModel' : ActorMethod<[string], boolean>,
  'deleteFinancialRule' : ActorMethod<[string], boolean>,
  'deleteGoal' : ActorMethod<[string], boolean>,
  'deleteLoan' : ActorMethod<[string], boolean>,
  'deletePlannerEvent' : ActorMethod<[string], boolean>,
  'deletePortfolioHolding' : ActorMethod<[string], boolean>,
  'deleteTransaction' : ActorMethod<[string], boolean>,
  'getAllBudgetCategories' : ActorMethod<[], Array<BudgetCategory>>,
  'getAllFinancialModels' : ActorMethod<[], Array<FinancialModel>>,
  'getAllFinancialRules' : ActorMethod<[], Array<FinancialRule>>,
  'getAllGoals' : ActorMethod<[], Array<Goal>>,
  'getAllLoans' : ActorMethod<[], Array<Loan>>,
  'getAllPlannerEvents' : ActorMethod<[], Array<PlannerEvent>>,
  'getAllPortfolioHoldings' : ActorMethod<[], Array<PortfolioHolding>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBudgetCategory' : ActorMethod<[string], [] | [BudgetCategory]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getFinancialModel' : ActorMethod<[string], [] | [FinancialModel]>,
  'getFinancialRule' : ActorMethod<[string], [] | [FinancialRule]>,
  'getGoal' : ActorMethod<[string], [] | [Goal]>,
  'getLoan' : ActorMethod<[string], [] | [Loan]>,
  'getNetWorth' : ActorMethod<[], number>,
  'getPlannerEvent' : ActorMethod<[string], [] | [PlannerEvent]>,
  'getPortfolioHolding' : ActorMethod<[string], [] | [PortfolioHolding]>,
  'getTransaction' : ActorMethod<[string], [] | [Transaction]>,
  'getUserModuleAccess' : ActorMethod<[], Array<[string, boolean]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerBlocked' : ActorMethod<[], BlockedStatus>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBudgetCategory' : ActorMethod<
    [string, BudgetCategory],
    [] | [BudgetCategory]
  >,
  'updateFinancialModel' : ActorMethod<
    [string, FinancialModel],
    [] | [FinancialModel]
  >,
  'updateFinancialRule' : ActorMethod<
    [string, FinancialRule],
    [] | [FinancialRule]
  >,
  'updateGoal' : ActorMethod<[string, Goal], [] | [Goal]>,
  'updateLoan' : ActorMethod<[string, Loan], [] | [Loan]>,
  'updatePlannerEvent' : ActorMethod<
    [string, PlannerEvent],
    [] | [PlannerEvent]
  >,
  'updatePortfolioHolding' : ActorMethod<
    [string, PortfolioHolding],
    [] | [PortfolioHolding]
  >,
  'updateTransaction' : ActorMethod<[string, Transaction], [] | [Transaction]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];