/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Goal {
    id: string;
    name: string;
    deadline: string;
    targetAmount: number;
    notes: string;
    category: string;
    currentAmount: number;
}
export interface FinancialRule {
    id: string;
    ruleType: string;
    action: string;
    threshold: number;
    name: string;
    isActive: boolean;
    condition: string;
}
export interface DashboardSummary {
    modelCount: bigint;
    totalIncome: number;
    loanCount: bigint;
    goalCount: bigint;
    budgetCategoryCount: bigint;
    totalExpenses: number;
    portfolioCount: bigint;
    eventCount: bigint;
    ruleCount: bigint;
    transactionCount: bigint;
}
export interface BudgetCategory {
    id: string;
    categoryType: TransactionType;
    monthlyLimit: number;
    name: string;
    color: string;
}
export interface PortfolioHolding {
    id: string;
    ticker: string;
    name: string;
    currentValue: number;
    notes: string;
    quantity: number;
    costBasis: number;
    assetType: AssetType;
}
export interface Loan {
    id: string;
    principal: number;
    currentBalance: number;
    name: string;
    loanType: string;
    termMonths: bigint;
    interestRate: number;
    notes: string;
    monthlyPayment: number;
    startDate: string;
}
export interface FinancialModel {
    id: string;
    name: string;
    initialAmount: number;
    notes: string;
    annualReturn: number;
    years: bigint;
    monthlyContribution: number;
}
export interface PlannerEvent {
    id: string;
    title: string;
    isCompleted: boolean;
    date: string;
    notes: string;
    amount: number;
    eventType: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface Transaction {
    id: string;
    categoryId: string;
    transactionType: TransactionType;
    date: string;
    description: string;
    account: string;
    amount: number;
}
export enum AssetType {
    ETF = "ETF",
    RealEstate = "RealEstate",
    MutualFund = "MutualFund",
    Commodity = "Commodity",
    FixedIncome = "FixedIncome",
    Crypto = "Crypto",
    Other = "Other",
    Retirement = "Retirement"
}
export enum TransactionType {
    Income = "Income",
    Expense = "Expense"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBudgetCategory(category: BudgetCategory): Promise<BudgetCategory>;
    createFinancialModel(model: FinancialModel): Promise<FinancialModel>;
    createFinancialRule(rule: FinancialRule): Promise<FinancialRule>;
    createGoal(goal: Goal): Promise<Goal>;
    createLoan(loan: Loan): Promise<Loan>;
    createPlannerEvent(event: PlannerEvent): Promise<PlannerEvent>;
    createPortfolioHolding(holding: PortfolioHolding): Promise<PortfolioHolding>;
    createTransaction(transaction: Transaction): Promise<Transaction>;
    deleteBudgetCategory(id: string): Promise<boolean>;
    deleteFinancialModel(id: string): Promise<boolean>;
    deleteFinancialRule(id: string): Promise<boolean>;
    deleteGoal(id: string): Promise<boolean>;
    deleteLoan(id: string): Promise<boolean>;
    deletePlannerEvent(id: string): Promise<boolean>;
    deletePortfolioHolding(id: string): Promise<boolean>;
    deleteTransaction(id: string): Promise<boolean>;
    getAllBudgetCategories(): Promise<Array<BudgetCategory>>;
    getAllFinancialModels(): Promise<Array<FinancialModel>>;
    getAllFinancialRules(): Promise<Array<FinancialRule>>;
    getAllGoals(): Promise<Array<Goal>>;
    getAllLoans(): Promise<Array<Loan>>;
    getAllPlannerEvents(): Promise<Array<PlannerEvent>>;
    getAllPortfolioHoldings(): Promise<Array<PortfolioHolding>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getBudgetCategory(id: string): Promise<BudgetCategory | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getFinancialModel(id: string): Promise<FinancialModel | null>;
    getFinancialRule(id: string): Promise<FinancialRule | null>;
    getGoal(id: string): Promise<Goal | null>;
    getLoan(id: string): Promise<Loan | null>;
    getNetWorth(): Promise<number>;
    getPlannerEvent(id: string): Promise<PlannerEvent | null>;
    getPortfolioHolding(id: string): Promise<PortfolioHolding | null>;
    getTransaction(id: string): Promise<Transaction | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBudgetCategory(id: string, category: BudgetCategory): Promise<BudgetCategory | null>;
    updateFinancialModel(id: string, model: FinancialModel): Promise<FinancialModel | null>;
    updateFinancialRule(id: string, rule: FinancialRule): Promise<FinancialRule | null>;
    updateGoal(id: string, goal: Goal): Promise<Goal | null>;
    updateLoan(id: string, loan: Loan): Promise<Loan | null>;
    updatePlannerEvent(id: string, event: PlannerEvent): Promise<PlannerEvent | null>;
    updatePortfolioHolding(id: string, holding: PortfolioHolding): Promise<PortfolioHolding | null>;
    updateTransaction(id: string, transaction: Transaction): Promise<Transaction | null>;
}
import type { AssetType as _AssetType, BudgetCategory as _BudgetCategory, FinancialModel as _FinancialModel, FinancialRule as _FinancialRule, Goal as _Goal, Loan as _Loan, PlannerEvent as _PlannerEvent, PortfolioHolding as _PortfolioHolding, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBudgetCategory(arg0: BudgetCategory): Promise<BudgetCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudgetCategory(to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BudgetCategory_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudgetCategory(to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BudgetCategory_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFinancialModel(arg0: FinancialModel): Promise<FinancialModel> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinancialModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinancialModel(arg0);
            return result;
        }
    }
    async createFinancialRule(arg0: FinancialRule): Promise<FinancialRule> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinancialRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinancialRule(arg0);
            return result;
        }
    }
    async createGoal(arg0: Goal): Promise<Goal> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0);
            return result;
        }
    }
    async createLoan(arg0: Loan): Promise<Loan> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoan(arg0);
            return result;
        }
    }
    async createPlannerEvent(arg0: PlannerEvent): Promise<PlannerEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlannerEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlannerEvent(arg0);
            return result;
        }
    }
    async createPortfolioHolding(arg0: PortfolioHolding): Promise<PortfolioHolding> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolioHolding(to_candid_PortfolioHolding_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PortfolioHolding_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolioHolding(to_candid_PortfolioHolding_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PortfolioHolding_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTransaction(arg0: Transaction): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(to_candid_Transaction_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Transaction_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(to_candid_Transaction_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Transaction_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBudgetCategory(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudgetCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudgetCategory(arg0);
            return result;
        }
    }
    async deleteFinancialModel(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinancialModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinancialModel(arg0);
            return result;
        }
    }
    async deleteFinancialRule(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinancialRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinancialRule(arg0);
            return result;
        }
    }
    async deleteGoal(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async deleteLoan(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLoan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLoan(arg0);
            return result;
        }
    }
    async deletePlannerEvent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlannerEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlannerEvent(arg0);
            return result;
        }
    }
    async deletePortfolioHolding(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolioHolding(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolioHolding(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getAllBudgetCategories(): Promise<Array<BudgetCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBudgetCategories();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBudgetCategories();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFinancialModels(): Promise<Array<FinancialModel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFinancialModels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFinancialModels();
            return result;
        }
    }
    async getAllFinancialRules(): Promise<Array<FinancialRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFinancialRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFinancialRules();
            return result;
        }
    }
    async getAllGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGoals();
            return result;
        }
    }
    async getAllLoans(): Promise<Array<Loan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLoans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLoans();
            return result;
        }
    }
    async getAllPlannerEvents(): Promise<Array<PlannerEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlannerEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlannerEvents();
            return result;
        }
    }
    async getAllPortfolioHoldings(): Promise<Array<PortfolioHolding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPortfolioHoldings();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPortfolioHoldings();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetCategory(arg0: string): Promise<BudgetCategory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetCategory(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetCategory(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getFinancialModel(arg0: string): Promise<FinancialModel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialModel(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialModel(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialRule(arg0: string): Promise<FinancialRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialRule(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialRule(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoal(arg0: string): Promise<Goal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoal(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoal(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoan(arg0: string): Promise<Loan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoan(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoan(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNetWorth(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetWorth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetWorth();
            return result;
        }
    }
    async getPlannerEvent(arg0: string): Promise<PlannerEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlannerEvent(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlannerEvent(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioHolding(arg0: string): Promise<PortfolioHolding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioHolding(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioHolding(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: string): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBudgetCategory(arg0: string, arg1: BudgetCategory): Promise<BudgetCategory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudgetCategory(arg0, to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudgetCategory(arg0, to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFinancialModel(arg0: string, arg1: FinancialModel): Promise<FinancialModel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinancialModel(arg0, arg1);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinancialModel(arg0, arg1);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFinancialRule(arg0: string, arg1: FinancialRule): Promise<FinancialRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinancialRule(arg0, arg1);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinancialRule(arg0, arg1);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGoal(arg0: string, arg1: Goal): Promise<Goal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0, arg1);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0, arg1);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLoan(arg0: string, arg1: Loan): Promise<Loan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLoan(arg0, arg1);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLoan(arg0, arg1);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePlannerEvent(arg0: string, arg1: PlannerEvent): Promise<PlannerEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlannerEvent(arg0, arg1);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlannerEvent(arg0, arg1);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePortfolioHolding(arg0: string, arg1: PortfolioHolding): Promise<PortfolioHolding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePortfolioHolding(arg0, to_candid_PortfolioHolding_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePortfolioHolding(arg0, to_candid_PortfolioHolding_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTransaction(arg0: string, arg1: Transaction): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, to_candid_Transaction_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, to_candid_Transaction_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AssetType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetType): AssetType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetCategory): BudgetCategory {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioHolding_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioHolding): PortfolioHolding {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BudgetCategory]): BudgetCategory | null {
    return value.length === 0 ? null : from_candid_BudgetCategory_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FinancialModel]): FinancialModel | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FinancialRule]): FinancialRule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Goal]): Goal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Loan]): Loan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlannerEvent]): PlannerEvent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioHolding]): PortfolioHolding | null {
    return value.length === 0 ? null : from_candid_PortfolioHolding_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ticker: string;
    name: string;
    currentValue: number;
    notes: string;
    quantity: number;
    costBasis: number;
    assetType: _AssetType;
}): {
    id: string;
    ticker: string;
    name: string;
    currentValue: number;
    notes: string;
    quantity: number;
    costBasis: number;
    assetType: AssetType;
} {
    return {
        id: value.id,
        ticker: value.ticker,
        name: value.name,
        currentValue: value.currentValue,
        notes: value.notes,
        quantity: value.quantity,
        costBasis: value.costBasis,
        assetType: from_candid_AssetType_n17(_uploadFile, _downloadFile, value.assetType)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    transactionType: _TransactionType;
    date: string;
    description: string;
    account: string;
    amount: number;
}): {
    id: string;
    categoryId: string;
    transactionType: TransactionType;
    date: string;
    description: string;
    account: string;
    amount: number;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        transactionType: from_candid_TransactionType_n9(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        account: value.account,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryType: _TransactionType;
    monthlyLimit: number;
    name: string;
    color: string;
}): {
    id: string;
    categoryType: TransactionType;
    monthlyLimit: number;
    name: string;
    color: string;
} {
    return {
        id: value.id,
        categoryType: from_candid_TransactionType_n9(_uploadFile, _downloadFile, value.categoryType),
        monthlyLimit: value.monthlyLimit,
        name: value.name,
        color: value.color
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Income: null;
} | {
    Expense: null;
}): TransactionType {
    return "Income" in value ? TransactionType.Income : "Expense" in value ? TransactionType.Expense : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ETF: null;
} | {
    RealEstate: null;
} | {
    MutualFund: null;
} | {
    Commodity: null;
} | {
    FixedIncome: null;
} | {
    Crypto: null;
} | {
    Other: null;
} | {
    Retirement: null;
}): AssetType {
    return "ETF" in value ? AssetType.ETF : "RealEstate" in value ? AssetType.RealEstate : "MutualFund" in value ? AssetType.MutualFund : "Commodity" in value ? AssetType.Commodity : "FixedIncome" in value ? AssetType.FixedIncome : "Crypto" in value ? AssetType.Crypto : "Other" in value ? AssetType.Other : "Retirement" in value ? AssetType.Retirement : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BudgetCategory>): Array<BudgetCategory> {
    return value.map((x)=>from_candid_BudgetCategory_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioHolding>): Array<PortfolioHolding> {
    return value.map((x)=>from_candid_PortfolioHolding_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n21(_uploadFile, _downloadFile, x));
}
function to_candid_AssetType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): _AssetType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_BudgetCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetCategory): _BudgetCategory {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PortfolioHolding_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioHolding): _PortfolioHolding {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ticker: string;
    name: string;
    currentValue: number;
    notes: string;
    quantity: number;
    costBasis: number;
    assetType: AssetType;
}): {
    id: string;
    ticker: string;
    name: string;
    currentValue: number;
    notes: string;
    quantity: number;
    costBasis: number;
    assetType: _AssetType;
} {
    return {
        id: value.id,
        ticker: value.ticker,
        name: value.name,
        currentValue: value.currentValue,
        notes: value.notes,
        quantity: value.quantity,
        costBasis: value.costBasis,
        assetType: to_candid_AssetType_n13(_uploadFile, _downloadFile, value.assetType)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    transactionType: TransactionType;
    date: string;
    description: string;
    account: string;
    amount: number;
}): {
    id: string;
    categoryId: string;
    transactionType: _TransactionType;
    date: string;
    description: string;
    account: string;
    amount: number;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        transactionType: to_candid_TransactionType_n5(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        account: value.account,
        amount: value.amount
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryType: TransactionType;
    monthlyLimit: number;
    name: string;
    color: string;
}): {
    id: string;
    categoryType: _TransactionType;
    monthlyLimit: number;
    name: string;
    color: string;
} {
    return {
        id: value.id,
        categoryType: to_candid_TransactionType_n5(_uploadFile, _downloadFile, value.categoryType),
        monthlyLimit: value.monthlyLimit,
        name: value.name,
        color: value.color
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): {
    ETF: null;
} | {
    RealEstate: null;
} | {
    MutualFund: null;
} | {
    Commodity: null;
} | {
    FixedIncome: null;
} | {
    Crypto: null;
} | {
    Other: null;
} | {
    Retirement: null;
} {
    return value == AssetType.ETF ? {
        ETF: null
    } : value == AssetType.RealEstate ? {
        RealEstate: null
    } : value == AssetType.MutualFund ? {
        MutualFund: null
    } : value == AssetType.Commodity ? {
        Commodity: null
    } : value == AssetType.FixedIncome ? {
        FixedIncome: null
    } : value == AssetType.Crypto ? {
        Crypto: null
    } : value == AssetType.Other ? {
        Other: null
    } : value == AssetType.Retirement ? {
        Retirement: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    Income: null;
} | {
    Expense: null;
} {
    return value == TransactionType.Income ? {
        Income: null
    } : value == TransactionType.Expense ? {
        Expense: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
